name: Deploy

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Delete directory contents on server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     script: |
      #       rm -rf ~/../../var/www/lauraemil.site/public_html/members/*
      - name: Copy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./*"
          target: "~/../../var/www/lauraemil.site/public_html/members"
          command_opts: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -t -S none -l {{username}} sudo sh -c"
      